apiVersion: v1
kind: Service
metadata:
  namespace: server
  name: web-httpd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: web-httpd
---
apiVersion: v1
kind: Service
metadata:
  namespace: server
  name: was
spec:
  type: ClusterIP
  clusterIP: 10.100.100.100
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: was
